default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 3 } %>
  timeout: 5000

development:
  <<: *default
  database: db/sqlite3/development.sqlite3

test:
  <<: *default
  database: db/sqlite3/test.sqlite3

production:
  <<: *default
  database: db/sqlite3/production.sqlite3
